[
    "universidade de bras\u00edlia",
    "Universit\u00e9 Paul Sabatier III",
    "University",
    "University Erlangen N\u00fcrnberg",
    "University of AAA",
    "University of AAA Niggers",
    "University of Aberdeen",
    "University of Adelaide",
    "University of Arizona",
    "University of BBB",
    "University of California",
    "University of Cambridg",
    "University of Cambridg modified",
    "University of Cambridge",
    "University of Cambridge MODFy",
    "University of ctw",
    "university of delhi",
    "University of Erlangen N\u00fcrnber",
    "university of finland",
    "University of Lag",
    "University of Manitoba",
    "University of Michigan",
    "University of Michigan12",
    "university of moscow",
    "university of mumbai",
    "University of Nelsonianos",
    "University of Oxford",
    "University of Phoenix",
    "university of school",
    "University of shubham naik",
    "University of Virginia",
    "University of Wisconsin-Milwaukee"
]
